version: "4.0"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://postgres:example@database:5432/postgres
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8080:8080"
    restart: always
    tty: true
    volumes:
      - /config:/config
      - /data:/data
  database:
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - /data/postgres:/var/lib/postgresql/data


volumes:
  config:
  data: