name: docker

concurrency:   
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  BASENAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
  REGISTRY: hub.docker.com # ghcr.io 
  IMAGE_TAG: latest

on:
  pull_request:
    branches: [ main, master ]
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main, master ]
  release:
    types: [ published ]
  workflow_dispatch:

permissions: write-all

jobs:
  application:
    env:
      # IMAGE: ${{ github.repository }}
      IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
    - 
      name: checkout
      uses: actions/checkout@v4
    - 
      id: meta
      name: docker metadata
      uses: docker/metadata-action@v5
      with:
        flavor: latest=true
        images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha  
    -
      name: setup qemu
      uses: docker/setup-qemu-action@v3
    -
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: authenticate
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    -
      id: push
      name: build and push
      uses: docker/build-push-action@v6
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        file: ./Dockerfile
        github-token: ${{ secrets.GITHUB_TOKEN }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}