name: docker

env:
  BASENAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
  REGISTRY: hub.docker.com # ghcr.io
  IMAGE_TAG: latest

on:
  pull_request:
    branches: [ main, master ]
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main, master ]
  schedule:
    - cron: "30 9 * * 5" # every Friday at 09:30 UTC
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        context: .
        dockerfile: Dockerfile
        name: ${{ env.BASENAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        platforms: linux/amd64,linux/arm64
        snapshot: true
        tags: ${{ env.IMAGE_TAG }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}